### NumPy 특징
- 과학 기술 계산을 위한 라이브러리를 제공
- 백터/행렬/배열 처리 및 연산, 난수 발생
- 파일관리(txt, csv 등 파일 읽기/쓰기)
- 리스트(list)형 데이터와 유사하지만 Numpy는 배열의 특징을 가짐
- 모든 원소는 동일한 자료형이어야 한다.
- 원소들 중 다른 자료형이 있다면 가장 큰 자료형으로 변경됨
- 계산 속도가 빠르다.
- 백터/연산, 배열 인덱싱 등을 통해 질의 가능

In [1]:
import numpy as np

### 벡터(1차원 배열) 구조 이해

In [6]:
lst=[1,2,3,4,5,6]
s = [i * 2 for i in lst]
print(type(lst))
s

<class 'list'>


[2, 4, 6, 8, 10, 12]

In [8]:
arr_lst=np.array(lst)
print(type(arr_lst))
arr_lst               # 벡터형

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [9]:
arr_lst*2

array([ 2,  4,  6,  8, 10, 12])

In [12]:
np.array(lst)*2

array([ 2,  4,  6,  8, 10, 12])

numpy 연산

In [16]:
arr1=np.array([1,2,3])
arr2=np.array([10,20,30])

print(arr1+arr2)
print(arr2>=20)


[11 22 33]
[False  True  True]


넘파이를 두 벡터 연산시 자료의 갯수가 동일해야 한다.

In [17]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30])

arr1+arr2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

### 2차원 배열 구조

In [25]:
import pandas as pd

lst=[[0,0,1], [8,12,33]]
print(lst[0])
print(lst[1])

df=pd.DataFrame(lst)
print(df.shape)
df

[0, 0, 1]
[8, 12, 33]
(2, 3)


0   1   2
0  0   0   1
1  8  12  33

In [27]:
arr=np.array(lst)
print(lst)
print(arr)

[[0, 0, 1], [8, 12, 33]]
[[ 0  0  1]
 [ 8 12 33]]


In [31]:
print(len(lst))   # lst의 전체 데이터 갯수
print(len(arr))   # arr의 행의 갯수

print(len(lst[0])) # lst의 첫번째 데이터의 갯수
print(len(arr[0])) # arr의 열의 갯수

2
2
3
3


In [33]:
lst=[[0,0,1,1], [8,12,33]]
arr=np.array(lst)
arr

<ipython-input-33-40a3ca4e79c8>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array(lst)


array([list([0, 0, 1, 1]), list([8, 12, 33])], dtype=object)

In [35]:
type(arr[0])

list

### 3차원 배열

In [42]:
lst=[[[10,20,30]]]
arr=np.array(lst)
print(arr.shape)
print(arr)

(1, 1, 3)
[[[10 20 30]]]


In [45]:
lst=[[[10,20,30],[15,25,35]]]
arr=np.array(lst)
print(arr.shape)
print(arr)

(1, 2, 3)
[[[10 20 30]
  [15 25 35]]]


In [46]:
lst=[[[10,20,30],[15,25,35]],[[1.,2.,3.],[12, 13.,15]]]
arr=np.array(lst)
print(arr.shape)
print(arr)

(2, 2, 3)
[[[10. 20. 30.]
  [15. 25. 35.]]

 [[ 1.  2.  3.]
  [12. 13. 15.]]]


In [47]:
lst=[[[10,20,30],[15,25,35]],[[1.,2.,3.],[12, 13.,15], [12, 13.,15]]]
arr=np.array(lst)
print(arr.shape)
print(arr)

(2,)
[list([[10, 20, 30], [15, 25, 35]])
 list([[1.0, 2.0, 3.0], [12, 13.0, 15], [12, 13.0, 15]])]


<ipython-input-47-3a62c14d0354>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array(lst)


In [48]:
lst=[[[10,20,30],[15,25,35]],[[1.,2.,3.],[12, 13.,"15"]]]
arr=np.array(lst)
print(arr.shape)
print(arr)

(2, 2, 3)
[[['10' '20' '30']
  ['15' '25' '35']]

 [['1.0' '2.0' '3.0']
  ['12' '13.0' '15']]]


### 파이썬 자료형
- NoneType / bool / int / float / complex / str / tuple / list / dict / function

In [52]:
from sys import getsizeof   # 변수의 메모리 사용 내역

a=1; b=1.;c="1"
print(getsizeof(a))
print(getsizeof(b))
print(getsizeof(c))

28
24
50


### 배열 구조 데이터 인덱싱

In [53]:
# 1차원 배열 인덱싱

arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[2])

10
50
30


In [61]:
# 2차원 배열의 인덱싱

arr=np.array([[10,20,30,40,50], [15,25,35,45,55]])
print(arr.shape)
print(arr,"\n")
print(arr[0])       # 첫번째 행 전체
print(arr[-1])      # 마지막행 전체
print(arr[0, 0])    # 첫번째 행의 첫번째 열
print(arr[-1, 2])   # 마지막 행의 세번째 열

(2, 5)
[[10 20 30 40 50]
 [15 25 35 45 55]] 

[10 20 30 40 50]
[15 25 35 45 55]
10
35


In [62]:
# 3차원 배열의 인덱싱
arr=np.array([[[10,20,30],[15,25,35]],[[1.,2.,3.],[12, 13.,15]]])
print(arr.shape)
print(arr, "\n")

(2, 2, 3)
[[[10. 20. 30.]
  [15. 25. 35.]]

 [[ 1.  2.  3.]
  [12. 13. 15.]]] 



In [68]:
print(arr[0],"\n")       # 첫면
print(arr[-1],"\n")      # 마지막 면
print(arr[0, 0],"\n")    # 첫면의 첫행
print(arr[-1, -1],"\n")  # 마지막 면의 마지막 행
print(arr[0, 0, 0],"\n")   # 첫면의 첫행 첫열
print(arr[-1, -1, -1],"\n") # 마지막 면의 마지막 행 마지막 열

[[10. 20. 30.]
 [15. 25. 35.]] 

[[ 1.  2.  3.]
 [12. 13. 15.]] 

[10. 20. 30.] 

[12. 13. 15.] 

10.0 

15.0 



불리언(Boolean) 배열 방식을 이용한 인덱싱

In [75]:
arr=np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
atf=np.array([False,True,False,True,False,True,False,True,False,True])  # True인 값만 매칭해 출력
print(arr[atf])            # True인 값만 매칭해 출력
anum=np.array([0,2,4,6,8])  
print(arr[anum])           # anum을 위치값으로 사용해 출력

[ 2  4  6  8 10]
[1 3 5 7 9]


In [80]:
arr[arr%2==1]   # arr에서 홀수 데이터 추출

array([1, 3, 5, 7, 9])

In [83]:
arr[arr%2==0]   # arr에서 짝수 데이터 추출

array([ 2,  4,  6,  8, 10])

In [85]:
arr=np.array([[10,20,30],[15,25,35],[1.,2.,3.],[12, 13.,15]])
arr

array([[10., 20., 30.],
       [15., 25., 35.],
       [ 1.,  2.,  3.],
       [12., 13., 15.]])

In [86]:
arr[:, [True, False, True]]   # 행 전체, 열은 True인 열만

array([[10., 30.],
       [15., 35.],
       [ 1.,  3.],
       [12., 15.]])

In [87]:
arr[[1,3], :]

array([[15., 25., 35.],
       [12., 13., 15.]])

### 배열 생성/구조 변경

배열 데이터 생성

In [88]:
arr=np.array([15,25,35,45])
arr.dtype

dtype('int32')

In [89]:
arr=np.array([15,25,35,45], dtype='f')   # 입력 데이터를 모두 float 형식으로 변경
arr.dtype

dtype('float32')

In [90]:
arr[1]=28
arr

array([15., 28., 35., 45.], dtype=float32)

In [92]:
arr=np.arange(1, 10, 2)  # 시작, 끝(포함하지 않음), 단계  => range() 함수와 동일하나 결과가 배열구조
arr.dtype

dtype('int32')

In [131]:
# 등간격 리스트
arr=np.logspace(1, 10, 10, endpoint=True, base=2)  # 시작, 끝, 개숫  / endpoint 옵션: 마지막 값 표현
print(arr)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [100]:
# 일정 간격
arr=np.linspace(0, 113, 5)  # 시작, 끝, 구간수   / endpoint 옵션: 마지막 값 표현
arr

array([  0.  ,  28.25,  56.5 ,  84.75, 113.  ])

배열 데이터 변경

In [110]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr_res=arr.reshape(2, 5)  # 배열 구조 변경 reshape(행갯수, 열갯수), 행*열한 값이 데이터 갯수와 같아야 함
arr_res

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [123]:
arr=np.arange(1, 51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [124]:
arr_res=arr.reshape(-1, 5)   # 행, 또는 열의 위치에 -1을 넣은 경우 행/열 자동 생성
arr_res

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [125]:
arr=np.arange(1, 52)
arr_res=arr.reshape(3, -1) 
arr_res

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34],
       [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51]])

In [126]:
arr_res.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51]])

In [137]:
arr=np.arange(1, 61).reshape(2, -1,  5)   # 3차원으로 변경
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [138]:
arr.reshape(-1)    # 1차원으로 변경

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

배열 데이터 수정

In [139]:
arr_res=arr.reshape(-1, 6)
arr_res

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [140]:
arr_res[0]=0
arr_res

array([[ 0,  0,  0,  0,  0,  0],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [141]:
arr_res[0, 2]=10         # arr_res[0][2]=10
arr_res

array([[ 0,  0, 10,  0,  0,  0],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

브로드캐스팅 (broad casting)  &  마스킹(masking)
- 하나의 배열or 요소가 어떤 특정 배열에 영향을 미칠때 배열간의 형상을 맞추는 것을 브로드 캐스팅이라고 함

In [142]:
# arr_res 배열에서 값을 나누고 남은 나머지가 0이면 True 반환
#idx변수를 만들어 (= masking을 만듬) true/false로 변환된 데이터를 저장) 
idx=arr_res%2==0
idx

array([[ True,  True,  True,  True,  True,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [143]:
# 만들어진 idx의 마스킹 값을 기준으로 True인 값만 출력
arr_res[idx]

array([ 0,  0, 10,  0,  0,  0,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28,
       30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [144]:
arr_res[idx]=100
arr_res

array([[100, 100, 100, 100, 100, 100],
       [  7, 100,   9, 100,  11, 100],
       [ 13, 100,  15, 100,  17, 100],
       [ 19, 100,  21, 100,  23, 100],
       [ 25, 100,  27, 100,  29, 100],
       [ 31, 100,  33, 100,  35, 100],
       [ 37, 100,  39, 100,  41, 100],
       [ 43, 100,  45, 100,  47, 100],
       [ 49, 100,  51, 100,  53, 100],
       [ 55, 100,  57, 100,  59, 100]])

### NumPy에서 파일 읽고/쓰기

In [160]:
with open('c:/pydata/test.csv', encoding='utf-8') as f:
    csv_data=[]
    for line in f.readlines():
        csv_data.append(line.split(","))
csv_data

[['a', '10', '\n'],
 ['b', '25', '\n'],
 ['c', '48', '\n'],
 ['d', '55', '\n'],
 ['e', '84', 'y\n'],
 ['f', '55', '\n'],
 ['g', '88', 'y\n'],
 ['h', '', '\n']]

In [158]:
import pandas as pd
df=pd.read_csv('c:/pydata/test.csv', encoding='utf-8', names=['이름', '값'])
df

이름    값
a  10.0  NaN
b  25.0  NaN
c  48.0  NaN
d  55.0  NaN
e  84.0    y
f  55.0  NaN
g  88.0    y
h   NaN  NaN

In [164]:
np_data=np.loadtxt('c:/pydata/test.csv', encoding='utf-8', delimiter=",", dtype=str)
np_data

array([['a', '10', ''],
       ['b', '25', ''],
       ['c', '48', ''],
       ['d', '55', ''],
       ['e', '84', 'y'],
       ['f', '55', ''],
       ['g', '88', 'y'],
       ['h', '', '']], dtype='<U2')

In [165]:
idx=np_data==""
idx

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False,  True,  True]])

In [171]:
np_data[idx]=0
print(np_data)

[['a' '10' '0']
 ['b' '25' '0']
 ['c' '48' '0']
 ['d' '55' '0']
 ['e' '84' 'y']
 ['f' '55' '0']
 ['g' '88' 'y']
 ['h' '0' '0']]


### NaN 변경하기

In [168]:
arr=np.array([5, 6, np.NaN])
arr

array([ 5.,  6., nan])

In [172]:
np.isnan(arr)      # panas.isnull

array([False, False,  True])

In [174]:
np.nan_to_num(arr)     # NaN 0을 변경

array([5., 6., 0.])

In [177]:
# np.isnan(arr) : arr에서 nan인 데이터에 대해서 True
arr[np.isnan(arr)]=5.5    # np.isnan()와 브로드캐스팅을 이용해 원하는 값으로 수정
arr

array([5. , 6. , 5.5])

In [188]:
arr=np.array([5, 6, np.NaN])
arr[np.isnan(arr)]=sum(np.nan_to_num(arr))/sum(np.isnan(arr)==False)
arr

array([5. , 6. , 5.5])

In [213]:
# np.isfinite(arr) : NaN이 아닌 값에 대해서 True, np.isnan의 반대
arr=np.array([5, 6, np.NaN])
np.isfinite(arr)

array([ True,  True, False])

In [214]:
arr=np.array([5, 6, np.NaN])
arr[np.isnan(arr)]=np.mean(arr[np.isfinite(arr)])
arr

array([5. , 6. , 5.5])

In [189]:
arr=np.array([5, 6, np.NaN])
arr[np.isnan(arr)]=np.mean(np.nan_to_num(arr))
arr

array([5.        , 6.        , 3.66666667])

### 행렬 데이터의 결합, concatenate 함수
- np.concatenate((a, b))

In [200]:
arr1=np.random.randint(10, size=(2, 3))   # 0~9 사이의 정수를 이용해 2행 3열 구조 데이터 생성
arr2=np.random.randint(10, size=(3, 2))   # 0~9 사이의 정수를 이용해 3행 2열 구조 데이터 생성
arr3=np.random.randint(10, size=(3, 3))   # 0~9 사이의 정수를 이용해 3행 3열 구조 데이터 생성

print(arr1)
print(arr2)
print(arr3)

[[3 5 8]
 [6 4 4]]
[[1 8]
 [6 4]
 [2 3]]
[[5 4 0]
 [8 5 8]
 [0 8 5]]


세로 결합(기본결합): 결합하고자 하는 열의 갯수 일치

In [201]:
np.concatenate((arr1, arr3))

array([[3, 5, 8],
       [6, 4, 4],
       [5, 4, 0],
       [8, 5, 8],
       [0, 8, 5]])

가로 결합: 병합하고자 하는 행의 갯수 일치

In [202]:
np.concatenate((arr2, arr3), axis=1)

array([[1, 8, 5, 4, 0],
       [6, 4, 8, 5, 8],
       [2, 3, 0, 8, 5]])

In [203]:
np.concatenate((arr1, arr3), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3